"""
The cross-learnings hub — where the Disney network effect actually happens,
now with k-anonymity and untrusted-inbound marking.

Each tenant contributes anonymized `cross_learning` signals (never raw content).
The hub pools them and redistributes: every consuming tenant receives learnings
generated by ALL contributing tenants. That is how a travel copilot's preference
insight sharpens a retail copilot's answers without either seeing the other's
private data.

Two 2025-2026 hardening additions:

  - k-ANONYMITY: a single verbatim learning can re-identify an individual even
    with zero regex-detectable PII (a unique event is itself identifying). So a
    learning only becomes DISTRIBUTABLE once at least `min_k` similar learnings
    exist (same domain + similar normalized text). Below k it waits in a pending
    buffer. This turns "anonymized" from a hope into a threshold.

  - UNTRUSTED INBOUND: learnings flow back DOWN to every tenant, so a poisoned
    learning is a cross-tenant prompt-injection vector. Distributed learnings
    are explicitly marked `trusted=False` so a consuming tenant treats them as
    untrusted content, not instructions.
"""
from __future__ import annotations

import re
from collections import defaultdict
from dataclasses import dataclass, field

_WORD = re.compile(r"[a-z0-9]+")


def _norm_key(domain: str, lesson: str) -> str:
    """A coarse similarity key: domain + sorted significant word set."""
    words = sorted(set(_WORD.findall(lesson.lower())))
    return f"{domain}|{' '.join(words[:12])}"


@dataclass
class SharedLearning:
    """One anonymized lesson available to consuming tenants."""

    source_tenant: str
    domain: str
    lesson: str
    reward_score: float
    trusted: bool = True     # flipped to False when it leaves the hub (inbound-untrusted)


@dataclass
class CrossLearningHub:
    """Pools anonymized learnings and redistributes them across tenants."""

    min_k: int = 1           # k-anonymity: learnings distribute only when >= k similar exist
    _distributable: list[SharedLearning] = field(default_factory=list)
    _pending: dict[str, list[SharedLearning]] = field(
        default_factory=lambda: defaultdict(list)
    )
    _by_domain: dict[str, list[SharedLearning]] = field(
        default_factory=lambda: defaultdict(list)
    )

    def contribute(self, learning: SharedLearning) -> bool:
        """Add a learning. Returns True if it became distributable now.

        If min_k > 1, the learning waits in a pending bucket keyed by
        (domain + similar text) until at least min_k similar learnings exist;
        then the whole bucket is promoted to distributable at once.
        """
        if self.min_k <= 1:
            self._promote(learning)
            return True
        key = _norm_key(learning.domain, learning.lesson)
        self._pending[key].append(learning)
        if len(self._pending[key]) >= self.min_k:
            for ln in self._pending.pop(key):
                self._promote(ln)
            return True
        return False

    def _promote(self, learning: SharedLearning) -> None:
        self._distributable.append(learning)
        self._by_domain[learning.domain].append(learning)

    def distribute(self, to_tenant_id: str, exclude_own: bool = True) -> list[SharedLearning]:
        """Learnings a tenant should absorb — from OTHER tenants, marked untrusted."""
        out = []
        for ln in self._distributable:
            if exclude_own and ln.source_tenant == to_tenant_id:
                continue
            # inbound is untrusted: hand back a copy flagged trusted=False
            out.append(
                SharedLearning(
                    source_tenant=ln.source_tenant, domain=ln.domain,
                    lesson=ln.lesson, reward_score=ln.reward_score, trusted=False,
                )
            )
        return out

    @property
    def _learnings(self) -> list[SharedLearning]:
        """All distributable learnings (persistence + coverage read this)."""
        return self._distributable

    def coverage(self) -> dict:
        """Proof-of-life for the network effect."""
        sources = {ln.source_tenant for ln in self._distributable}
        pending = sum(len(v) for v in self._pending.values())
        return {
            "total_learnings": len(self._distributable),
            "pending_below_k": pending,
            "contributing_tenants": len(sources),
            "domains": sorted(self._by_domain.keys()),
            "is_networked": len(sources) >= 2,
            "min_k": self.min_k,
        }
