"""
The cross-learnings hub — where the Disney network effect actually happens.

Each tenant contributes anonymized `cross_learning` signals (never raw content).
The hub pools them and redistributes: every consuming tenant receives the
learnings generated by ALL contributing tenants. This is the mechanism by which
a travel copilot's preference insight sharpens a retail copilot's answers,
without either seeing the other's private data.

If this hub stays empty, you have per-tenant self-improvement but NOT a flywheel.
`coverage()` exists so you can prove the loop is actually populated.
"""
from __future__ import annotations

from collections import defaultdict
from dataclasses import dataclass, field


@dataclass
class SharedLearning:
    """One anonymized lesson available to all consuming tenants."""

    source_tenant: str
    domain: str
    lesson: str
    reward_score: float


@dataclass
class CrossLearningHub:
    """Pools anonymized learnings and redistributes them across tenants."""

    _learnings: list[SharedLearning] = field(default_factory=list)
    _by_domain: dict[str, list[SharedLearning]] = field(
        default_factory=lambda: defaultdict(list)
    )

    def contribute(self, learning: SharedLearning) -> None:
        self._learnings.append(learning)
        self._by_domain[learning.domain].append(learning)

    def distribute(self, to_tenant_id: str, exclude_own: bool = True) -> list[SharedLearning]:
        """Learnings this tenant should absorb — those from OTHER tenants."""
        if exclude_own:
            return [ln for ln in self._learnings if ln.source_tenant != to_tenant_id]
        return list(self._learnings)

    def coverage(self) -> dict:
        """Proof-of-life for the network effect: how many tenants/domains feed it."""
        sources = {ln.source_tenant for ln in self._learnings}
        return {
            "total_learnings": len(self._learnings),
            "contributing_tenants": len(sources),
            "domains": sorted(self._by_domain.keys()),
            "is_networked": len(sources) >= 2,   # >=2 sources = real cross-pollination
        }
